// <auto-generated />
using FirstAPITest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPITest.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    [Migration("20260210213120_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPITest.Models.Microcontroller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClockFz")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Microcontrollers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClockFz = 480,
                            Manufacturer = "Espressif",
                            Model = "ESP32S3"
                        },
                        new
                        {
                            Id = 2,
                            ClockFz = 240,
                            Manufacturer = "Espressif",
                            Model = "ESP32C3"
                        },
                        new
                        {
                            Id = 3,
                            ClockFz = 16,
                            Manufacturer = "Arduino",
                            Model = "UNO"
                        },
                        new
                        {
                            Id = 4,
                            ClockFz = 16,
                            Manufacturer = "Arduino",
                            Model = "Nano"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
