@rootURL = http://localhost:5284

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/MCU
Accept: application/json

###
GET {{rootURL}}/api/MCU/3
Accept: application/json

###
POST {{rootURL}}/api/MCU
Content-Type: application/json

{
    "model": "ESP8266",
    "manufacturer": "Espressif",
    "clockFz": 80
}

###
PUT {{rootURL}}/api/MCU/2
Content-Type: application/json

{
    "id": 2,
    "model": "ESP8266",
    "manufacturer": "Espressif",
    "clockfz": 80
}

###
DELETE {{rootURL}}/api/MCU/3
